### ISSUE TITLE
Создать интерфейс незарегистрированного пользователя(гость)

### ISSUE THREAD

**Issue by IlyaSvetlichnii** [esdp-2016-Team3/StepToUniverse#1]
Описание:
Необходимо создать гостевую информационную страницу

Функция: Базовый интерфейс для гостей

Сценарий тестирования:
Допустим я являюсь гостем
Если я нахожусь на главной странице сайта
То вижу шапку сайта с кнопками авторизации и регистрации
И вижу информационный текст организации

**Comment by Daniiar** [comment]
Time planned: 1

**Comment by Daniiar** [comment]
Time spent: 1
