### ISSUE TITLE
Cоздать функционал оповещения по email

### ISSUE THREAD

**Issue by IlyaSvetlichnii** [esdp-2016-Team3/StepToUniverse#10]
Описание: 
 После регистрации пользователя приходит сообщение на email администратору о запросе на подтверждение пользователя, после того как администратор отклонил или принял запрос, приходит оповещение пользователю с уведомлением о решении администратора.

Сценарии тестирования:

Функционал: Оповещение администратора
Допустим я администратор
Если пользователь успешно прошел регистрацию
То мне на почту(email) приходит уведомлении о запросе на подтверждение регистрации

Функционал: Оповещение пользователя
Допустим я анонимный пользователь прошедший регистрацию
Если администратор сайта отклонил или принял мой запрос
То мне на почту(email) приходит соответствующие оповещение о решении администратора

**Comment by danildf** [comment]
Time planned: 3
Time spent: 1 - разница из-за неправильной оценки объёма работы
