### ISSUE TITLE
Сверстать таблицу, "Наши преподаватели"

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#103]
**Предыстория:**
Нужно красивое отображение наших преподавателей.

**Задача:**
Сверстать таблицу, "Наши преподаватели"

**Методы решения:**
Бутстрап

**Сценарий тестирования:**
1) Зайти  в "Наши преподаватели"
2) Увидеть аккуратную таблицу

**Comment by Daniiar** [comment]
Time planned: 2
Time spent: 1
