### ISSUE TITLE
Сверстать страницу, "Список литературы"

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#105]
**Предыстория:**
Нужно красивое отображение Списка литературы в табличном виде.

**Задача:**
Сверстать страницу, "Список литературы"

**Методы решения:**
Бутстрап

**Сценарий тестирования:**
1) Зайти в "Список литературы"
2) Увидеть аккуратную таблицу.

**Comment by Daniiar** [comment]
Time planned: 1
Time spent: 1
