### ISSUE TITLE
Удалить лишние поле Pather со всех моделей

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#106]
**Предыстория:**
Удалить неиспользуемые поля.

**Задача:**
Удалить лишнее поле Pather со всех моделей

**Методы решения:**
В миграциях убрать поля

**Сценарий тестирования:**
1) Удаленные поля смотреть в rails c у моделей
2) Убедиться что их нету.
3) Убедиться что проект не работает.

**Comment by Daniiar** [comment]
Time planned: 2
Time spent: 1
