### ISSUE TITLE
Перейти на сервере, на новую БД PostgreSQL

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#115]
**Предыстория:**
Перейти на сервере, на новую БД PostgreSQL

**Задача:**
Перейти на сервере, на новую БД PostgreSQL

**Методы решения:**

**Сценарий тестирования:**
1) Убедиться что БД стоит и все работает)

**Comment by IlyaSvetlichnii** [comment]
Time planned: 1

**Comment by IlyaSvetlichnii** [comment]
Time planned 1.5
