### ISSUE TITLE
Разработать форму по созданию тестовых заданий

### ISSUE THREAD

**Issue by IlyaSvetlichnii** [esdp-2016-Team3/StepToUniverse#12]
Описание:
Есть форма с полем вопроса и поля вариантов ответа, есть возможность пометить правильность ответа. Есть возможность добавлять и удалять варианты ответов, есть возможность назначить уровень сложности вопроса

**Comment by IlyaSvetlichnii** [comment]
Time planned 5

**Comment by esdp-2016-Team3** [comment]
Time spent 6
