### ISSUE TITLE
Подобрать заместо выпадающего списка с датами, календарь. В отчете.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#123]
**Предыстория:**
Заказчик составил список багов и заметок на исправления.
10. Мы можем на форме подтверждения проведения занятия в ЛКП использовать более удобоваримый контрол для введения даты проведения занятий? Типа какой нить календарь? ну или что то вроде эдит-бокса с маской даты? Сейчас это выпадающий список с огромной кучей дат, в который очень легко запутаться.

**Задача:**
Подобрать заместо выпадающего списка с датами, календарь. В отчете.

**Методы решения:**
Гугл.

**Сценарий тестирования:**
1) Убедиться что календарь работает.
2) Убедиться что все работает.

**Comment by IlyaSvetlichnii** [comment]
Time planned: 3

**Comment by IlyaSvetlichnii** [comment]
time spent: 4

**Comment by KarambaKG** [comment]
Проверено. Работает.
