### ISSUE TITLE
При регистрации преподавателя нет анкеты.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#124]
**Предыстория:**
При регистрации преподавателя нет анкеты.

**Задача:**
Написать в сиды, вопросы для преподавателя. Отобразить их в админке (Вопросы и ответы), в информации неактивного преподавателя.

**Методы решения:**

**Сценарий тестирования:**
1) Создать сиды, дропнуть базу, прогнать сиды.
2) Ответить на вопросы при регистрации, и подтвердить преподавателя.
3) Увидеть в админке, в запросах на регистрацию, ответы на вопросы.

**Comment by IlyaSvetlichnii** [comment]
Time planned: 3

**Comment by IlyaSvetlichnii** [comment]
Time spent: 9 - возникли проблемы с вложенностью в devise
