### ISSUE TITLE
В ЛКП при составлении расписания если НЕ выбрать студента и нажать кнопку "Сохранить студента" получу красную клетку с пустым именем.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#125]
**Предыстория:**
7. В ЛКП при составлении расписания если НЕ выбрать студента и нажать кнопку "Сохранить студента" получу красную клетку с пустым именем. Нельзя сохранять студента, не выбрав его.

**Задача:**
Если студент не выбран, не должна клетка краситься в красный свет.

**Методы решения:**

**Сценарий тестирования:**
1) Войти под преподом.
2) В расписании не выбрать студента и кликнуть сохранить
3) Увидеть что клетка осталась также зеленой

**Comment by IlyaSvetlichnii** [comment]
Time planned: 3

**Comment by IlyaSvetlichnii** [comment]
time spent: 2.5

**Comment by KarambaKG** [comment]
Проверено. Работает.
