### ISSUE TITLE
Не обнуляется расписание у учителя и студента, при смена учителя у студента.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#126]
**Предыстория:**
8. Если студенту поменять преподавателя, то в ЛКС расписание занятий остается ПРЕЖНИМ. То есть от старого преподавателя. Надо это расписание у него обнулять, до того момента, пока новый препод не назначит ему часы занятий. Если же у нового препода добавить время занятия для этого студента, то у этого студента в ЛКС будет отражаться ОБА расписания. 

**Задача:**
Нужно чтобы при смене студенту учителя. Обнулялось расписание у студента, а у преподавателя в расписании удалялся только этот студент.

**Методы решения:**

**Сценарий тестирования:**
1) Назначить студенту учителя 1.
2) Назначить студенту занятие у учителя 1
3) Назначить студенту учителя 2
4) Убедиться, что у студента обнулилось расписание
5) Убедиться, что у преподавателя в расписании исчез только этот студент.

**Comment by IlyaSvetlichnii** [comment]
Time planned: 2

**Comment by IlyaSvetlichnii** [comment]
time spent: 2

**Comment by KarambaKG** [comment]
Проверено. Работает.
