### ISSUE TITLE
Исправить ошибку в админке по созданию любого пользователя 

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#13]
**Шаги воспроизведения**
1. Захожу как администратор
2. Перехожу к списку студентов
3. Нажимаю на кнопку создать нового студента

**Наблюдаемое поведение**
Вижу ошибку "ActiveModel::ForbiddenAttributesError"

**Ожидаемое поведение**
Вижу данные о созданном студенте

Локальный компьютер Данияра, коммит ed6699e833a810ff15b8d7d85969c29d1e1eb35f

**Причины**

**Решение**

**Тесты**

**Comment by esdp-2016-Team3** [comment]
Time planned: 0.5

**Comment by esdp-2016-Team3** [comment]
Time spent 1
