### ISSUE TITLE
В ЛКП не отображаются ДЗ на проверку

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#133]
**Предыстория:**
Данияр тестировал отрпавку ДЗ студентом преподавателю, войдя как преподватель не увидел дз на проверку
**Задача:**
Отобразить непровереннные дз преподавателя
**Методы решения:**
**Сценарий тетстирования:**
1.Войти как препод1 и отправить дз студенту1
2.Войти как студент1 и выполнить дз препода1
3.Войти как препод1 и увидеть не проверенные дз с количеством
4.Проверить дз

**Comment by IlyaSvetlichnii** [comment]
Time planned: 1

**Comment by IlyaSvetlichnii** [comment]
time spent: 1.5
