### ISSUE TITLE
Создать систему пробного тестирования

### ISSUE THREAD

**Issue by danildf** [esdp-2016-Team3/StepToUniverse#14]
Описание:
Для всех пользователей(даже не залогиненных) нужно составить систему тестирования включающую 20 рандомных вопросов из БД, по 5 на каждый уровень сложности. Ответы должны выдаваться в рандомном порядке.

**Comment by esdp-2016-Team3** [comment]
Time planned: 3
Time spent: 5 - возникла проблема с построением контроллера, искали в хеше по ключу а надо было по значению
