### ISSUE TITLE
Исправить возможность создания онлайн вопроса с любым количеством правильных ответов (от 0 до количества вариантов)

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#16]
Шаги воспроизведения
1. Захожу как администратор
2. Перехожу к интерфейсу всех вопросов онлайн_тестирования
3. Создаю новый вопрос с помощью кнопки "создать вопрос"
4. Заполняю поле "Content"(вопрос)
5. Определяю из выпадающего списка "Level"( уровень) вопроса
6. Нажимаю на кнопку "добавить"(добавить вариант ответа)
7. Заполняю поле "Content"(вариант ответа)
8. Помечаю его "Is correct"(правильным)
9. Нажимаю на кнопку "добавить"(добавить вариант ответа)
10. Заполняю поле "Content"(вариант ответа)

Наблюдаемое поведение:
Вижу, что у меня есть возможность пометить второй вариант ответа правильным

Ожидаемое поведение:
Я не должен иметь возможности помечать правильным более одного варианта ответов в вопросе

Локальный компьютер Данияра, коммит 8020c8c686b8e69d8edbb572bba87bbe86cf9744

Причины

Решение

Тесты

**Comment by KarambaKG** [comment]
Все нормально. Это норма. Фича.
