### ISSUE TITLE
Отсутствует изменение статуса активности вопроса для онлайн тестирования после редактирования

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#18]
Шаги воспроизведения:
1. Захожу как администратор
2. Перехожу к интерфейсу всех вопросов онлайн_тестирования
3. Нажимаю на кнопку "изменить"
4. Ставлю пометку статуса вопроса "Is active"
5. Нажимаю кнопку сохранения "Update question"

Наблюдаемое поведение:
Вижу, что отредактированный вопрос не поменял статус

Ожидаемое поведение:
Вопрос должен поменять статус

Локальный компьютер Данияра, коммит 8020c8c686b8e69d8edbb572bba87bbe86cf9744

Причины

Решение

Тесты

**Comment by esdp-2016-Team3** [comment]
Time planned: 0.2

**Comment by esdp-2016-Team3** [comment]
Time spent: 0.1
