### ISSUE TITLE
Создать панель администратора с функционалом

### ISSUE THREAD

**Issue by IlyaSvetlichnii** [esdp-2016-Team3/StepToUniverse#2]
Описание:
Необходимо разработать функционал авторизации для входа систему администратором. 

Сценарии тестирования:

Функция: Администратор видит форму авторизации
Допустим я являюсь не авторизированым пользователем
Если я нахожусь в разделе админ
То вижу форму авторизации пользователя

Функция: Администратор успешно прошел авторизацию
Допустим я являюсь администратором
Если я успешно прошел авторизацию в разделе админ
То вижу интерфейс раздела администратор

Функция: Интерфейс администратора
Допустим я являюсь администратором
Если я нахожусь в разделе админ
То вижу разделы пользователей,преподавателей и ожидающих подтверждения регистрации
Перейдя в любой раздел я вижу список пользователей, просмотр какого либо пользователя,
редактирование данных и де активация пользователя

**Comment by danildf** [comment]
Time planned: 3

**Comment by IlyaSvetlichnii** [comment]
Time planned: 3
Time spent: 4

**Comment by IlyaSvetlichnii** [comment]
Time spent: 4
