### ISSUE TITLE
Создать приёмочные тесты для админки

### ISSUE THREAD

**Issue by danildf** [esdp-2016-Team3/StepToUniverse#20]
Сценарии тестирования:

Часть 1

Функция: Администратор видит форму авторизации
Допустим я являюсь не авторизированым пользователем
Если я нахожусь в разделе админ
То вижу форму авторизации пользователя
Cоздать систему тестирования админки:

Функция: Администратор успешно прошел авторизацию
Допустим я являюсь администратором
Если я успешно прошел авторизацию в разделе админ
То вижу интерфейс раздела администратор

Функция: Интерфейс администратора
Допустим я являюсь администратором
Если я нахожусь в разделе админ
То вижу разделы пользователей,преподавателей и ожидающих подтверждения регистрации
Перейдя в любой раздел я вижу список пользователей
В разделе Запросы на регистрацию могу подтвердить или отказать

**Comment by danildf** [comment]
Часть Time planned: 1
Time spent: 0.3

**Comment by fedyay** [comment]
Часть 2

Time planned: 1
