### ISSUE TITLE
Список литературы 

### ISSUE THREAD

**Issue by esdp-2016-Team3** [esdp-2016-Team3/StepToUniverse#28]
Описание: 
Просмотр материалов в раздели "список литературы" для анонимных пользователей и возможность скачать файл с литературой для студента, преподаватель может загружать материал

Сценарий тестирования:

Функционал: список литературы для неавторизованных пользователей
Допустим я неавторизованный пользователь
Если я перехожу в раздел список литературы
То я вижу список материалов
И могу читать описание описание

Функционал: список литературы для студентов
Допустим я студент
Если я перехожу в раздел список литературы
То я вижу список материалов
И могу читать описание
И скачивать материал

Функционал: список литературы для студентов
Допустим я студент
Если я перехожу в раздел список литературы
То я вижу список материалов
И могу читать описание
И скачивать материал
Также я могу загружать фаил

Функционал: я, как учитель добавляю литературу,
                      я, как админ удаляю,
                      я, как учитель не вижу свою добавленную литературу

  Сценарий: загрузка учителем книги,
                    удаление ее админом,
                    проверка учителем что книги нет

```
Допустим я как учитель1 логинюсь, добавляю книгу
Если я залогинен как админ и удаляю книгу добавленная от препода №1
То я как учитель1 больше не вижу мою удаленную книгу админом
```

**Comment by Daniiar** [comment]
Time planned: 10

**Comment by danildf** [comment]
Time spent: 2
