### ISSUE TITLE
Преподаватель может удалять только свои файлы в списке литературы

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#31]
Описание: Я, как пользователь захожу на главную страницу, затем авторизируюсь как учитель "Данияр", захожу в интерфейс списка литературы, добавляю новый файл, вижу в списке литературы добавленный мною файл, добавляю второй новый файл и вижу оба файла добавленные мною. Затем удаляю свой первый файл и вижу только второй файл добавленный мною. Выхожу из своего профиля как "Данияр".
   Затем авторизуюсь как учитель "Илья", захожу в интерфейс списка литературы и вижу что у меня есть возможность удалить файлы другого пользователя (учителя "Данияра").

**Comment by esdp-2016-Team3** [comment]
Time planned: 0.3

**Comment by esdp-2016-Team3** [comment]
Time spent: 0.3
