### ISSUE TITLE
Создать валидацию на вопросы онлайн тестирования для посетителей сайта(для гостей)

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#35]
Описание: Создать валидацию для онлайн тестирования, чтобы тест не завершался пока пользователь не ответит на все вопросы.

Сценарии тестирования:
Я, как гость, нахожусь на главной странице, нажимаю на кнопку "Пробный тест", перехожу на страницу c тестами, отвечаю на половину вопросов и вижу что я у меня есть возможность завершить тест без ответов на не отвеченные вопросы.

**Comment by danildf** [comment]
Time planned: 1

**Comment by danildf** [comment]
Time spent: 1
