### ISSUE TITLE
Передвинуть радио-кнопки(radio-button) вопросов онлайн тестирования

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#36]
Описание: Я, как гость, нахожусь на главной странице, нажимаю на кнопку "Пробный тест", перехожу на страницу c тестами, отвечаю на вопросы, радио-кнопки находятся слева.

Улучшить: необходимо радиокнопки(radio-button) передвинуть влево, чтобы вопрос начинался с радиокнопок(radio-button)

**Comment by danildf** [comment]
Time planned: 0.2

**Comment by danildf** [comment]
Time spent: 0.2
