### ISSUE TITLE
Добавить в интерфейс администратора список литературы(с функционалом CRUD)

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#37]
Описание: Необходимо добавить в интерфейс администатора "Список литературы" с функционалом "CRUD"

Сценарий тестирования:
Я, администратор, вижу в моем интерфейсе "Список литературы", перехожу к списку литературы и могу удалять, просматривать, редактировать и создавать любую литературу

**Comment by esdp-2016-Team3** [comment]
Time planned: 0.5

**Comment by esdp-2016-Team3** [comment]
Time spent: 0.3
