### ISSUE TITLE
Исправить ошибку у администратора в интерфейсе "Преподаватели"

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#38]
Шаги воспроизведения:
1. Захожу как администратор
2. Перехожу к интерфейсу "Преподаватели"

Наблюдаемое поведение:
Вижу ошибку "LoadError in Admin::TeachersController#index"

Ожидаемое:
Вижу список преподавателей

Локальный компьютер Данияра

Причины

Решение

Тесты

**Comment by danildf** [comment]
Time planned: 0.5

**Comment by fedyay** [comment]
Time spent: 0.5

**Comment by danildf** [comment]
Time spent: 1
