### ISSUE TITLE
Создать функционал авторизации пользователя

### ISSUE THREAD

**Issue by IlyaSvetlichnii** [esdp-2016-Team3/StepToUniverse#4]
Описание:
Необходимо разработать функционал авторизации для входа систему пользователей. В систему могут залогиниться пользователи с ролями "студент" и "преподаватель".

Сценарии тестирования:

Функция: Анонимный пользователь видит форму авторизации
Допустим я являюсь анонимным пользователем
Если я нахожусь на главной странице сайта
То вижу форму авторизации пользователя

Функция: Авторизация в системе пользователя с ролью "преподаватель"
Допустим я зарегистрирован в системе как преподаватель
Если я логинюсь в системе под своим логином
То вижу главную страницу с функциями преподавателя

Функция: Авторизация в системе пользователя с ролью "студент"
Допустим я зарегистрирован в системе как студент
Если я логинюсь в системе под своим логином
То вижу главную страницу с функциями студента

Функция: Вывод сообщения об ошибке в случае ввода ошибочных реквизитов доступа
Допустим я зарегистрирован в системе
Если я ввожу неверный пароль
То вижу сообщение "Введён неправильный пароль или имя пользователя. Проверьте правильность введённых данных и повторите попытку."

**Comment by Daniiar** [comment]
Time planned: 4

**Comment by IlyaSvetlichnii** [comment]
Time planned: 2
Time spent: 4

**Comment by IlyaSvetlichnii** [comment]
Time spent: 4
