### ISSUE TITLE
Как преподаватель, не имею возможность удалить новую добавленную литературу

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#43]
Шаги воспроизведения:
1. захожу как преподаватель 1
2. захожу в интерфейс списка литературы
3. добавляю новую литературу

Наблюдаемое поведение:
Вижу, что у меня нету возможности удалить литературу добавленную мною

Ожидаемое поведение:
Я должен иметь возможность удалить литературу добавленную мною

Локальный компьютер Данияра

Причины:
нету скрытого поля присвающего данные автора в форме заполнения новой литературы(текущего пользователя(hidden_field))

Решение:
1. Присвоить данные (данные автора через скрытое поле(hidden_field))
2. Вытащить поле автора в администраторской части в интерфейсе списка литературы
3. Вытащить автора для гостевой страницы
4. Вытащить автора для студента
5. Вытащить автора для преподавателя

Тесты

**Comment by esdp-2016-Team3** [comment]
Time planned: 0.5

**Comment by esdp-2016-Team3** [comment]
Time spent: 0.5
