### ISSUE TITLE
В интерфейсе списка литературы в администраторской части вижу домашние задания

### ISSUE THREAD

**Issue by Daniiar** [esdp-2016-Team3/StepToUniverse#44]
Шаги воспроизведения:
1. Захожу как администратор
2. Перехожу в интерфейс списка литературы

Наблюдаемое поведение:
Вижу что тут имеются домашние задания преподавателей или студентов

Ожидаемое поведение:
Я вижу только литературу добавленные преподавателями и больше ничего

Решение:

Локальный компьютер Данияра

Причины

Тесты

**Comment by esdp-2016-Team3** [comment]
Time planned: 0.3

**Comment by esdp-2016-Team3** [comment]
Time spent: 0.5
