### ISSUE TITLE
Добавить функционал в ЛКП, создание ДЗ (теста).

### ISSUE THREAD

**Issue by IlyaSvetlichnii** [esdp-2016-Team3/StepToUniverse#45]
**Предыстория:**
Заказчик хочет, чтобы преподаватель мог составлять ДЗ (тесты) для студентов.

**Задача:**
Написать функционал создания теста, и добавить его в ЛКП, на странице "Домашние задания". Добавить кнопку "Создать тест". При клике на кнопку должно перейти в меню создания теста.
Должен сохраняться как обычная ДЗ. Добавить напротив теста кнопку "Удалить" на странице "Мои ДЗ"

**Методы решения:**

**Сценарий тестирования:**
1) Зайти под логином преподавателя
2) Зайти в ЛКП
3) Кликнуть "Домашние задания"
4) Кликнуть "Создать тест"
5) Создать тест и сохранить как ДЗ
6) Увидеть в списке домашних заданий тест
7) Удалить тест.
8) Убедиться что он удален.

**Comment by IlyaSvetlichnii** [comment]
Time planned: 5
Time spent: 10 - убрал модель Survey из за не надобности в связи с чем ушло много времени на перенос и фиксы багов

**Comment by KarambaKG** [comment]
Тикет проверен.
