### ISSUE TITLE
Добавить функционал в ЛКП. Запись аудио сообщения преподавателем

### ISSUE THREAD

**Issue by IlyaSvetlichnii** [esdp-2016-Team3/StepToUniverse#46]
**Предыстория:**
Заказчик хочет, чтобы в ЛКП преподаватель мог записать звуковое сообщение, сохранить его как ДЗ и отправить его студенту.

**Задача:**
В ЛКП. На странице "Мои ДЗ" добавить кнопку  "Записать звуковое сообщение". При клике на нее, должна открыться новая страница. На которой будет функционал записи сообщения.
Нужно найти плагин или гем для записи звука и установить его.

**Методы решения:**
Ищем в интернете.
http://subinsb.com/html5-record-mic-voice

**Сценарий тестирования:**
1) Зайти под логином преподавателя
2) Зайти в ЛКП
3) Зайти в "Мои ДЗ"
4) Зайти в "Записать звуковое сообщение"
5) Убедиться что звук записан и сохранен.

**Comment by KarambaKG** [comment]
Time planned: 125h

**Comment by KarambaKG** [comment]
Time spent: 24

**Comment by IlyaSvetlichnii** [comment]
Тикет проверен, описываемый функционал работает
