### ISSUE TITLE
Добавить функционал в ЛКП, вывод всех домашних заданий преподавателя.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#49]
**Предыстория:**
Заказчик пожелал в ЛКП видеть список всех домашних заданий, которые создает преподаватель. 

**Задача:**
В ЛКП нужно:
 Создать кнопку "Домашние задания преподавателя". При клике на неё, в новом окне выводятся все домашние задания, которые создал преподаватель.

**Методы решения:**
Создать кнопку, создать новую вьюшку.

**Сценарий тестирования:**
1) Зайти под логином преподавателя.
2) Зайти в ЛКП.
3) Увидеть кнопку "Домашние задания преподавателя" и кликнуть на неё. Вас должно перекинуть на новую страницу.
4) Увидеть список всех домашних заданий.

**Comment by IlyaSvetlichnii** [comment]
Time planned: 0.7
Time spent 0.4

**Comment by KarambaKG** [comment]
Тикет проверен. Работает.
