### ISSUE TITLE
Добавление функционала в ЛКП. Удаление и создание домашних заданий.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#50]
К этому тикету приступать только после выполнения #49 

**Предыстория:**
Заказчик сказал:  "Преподаватель может только создавать и удалять домашние задания"

**Задача:**
В ЛКП, в списке домашних заданий преподавателя, нужно напротив каждого задания добавить кнопку "Удалить". Перенести функционал создания домашнего задания с ЛКП, в окно списка всех домашних заданий.

**Методы решения:**
Написать Action Destroy, добавить роуты, добавить ссылку. Перенести функционал создания ДЗ.

**Сценарий тестирования:**
1) Зайти под логином преподавателя.
2) Зайти в ЛКП.
3) Увидеть кнопку "ДЗ преподавателя", кликнуть на неё.
4) Увидеть список ДЗ, кликнуть на "Создать ДЗ"
5) Убедиться что ДЗ появилось в списке.
6) Кликнуть напротив ДЗ кнопку "Удалить"
7) Убедиться, что ДЗ отсутствует в списке ДЗ.

**Comment by IlyaSvetlichnii** [comment]
Time planned: 1

**Comment by IlyaSvetlichnii** [comment]
Time spent: 1

**Comment by KarambaKG** [comment]
Тикет проверен, работает.
