### ISSUE TITLE
Добавить в Navbar кнопку для перехода на главную страницу сайта.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#51]
**Предыстория:**
Нужна кнопка перехода в Navbar на главную страницу сайта.

**Задача:**
localhost:3000 сделать рутовой страницей
В layouts, Логотип Step to you сделать кнопкой перехода на root_path

**Методы решения:**
В layouts, Логотип Step to you сделать ссылкой переходящей на root_path

**Сценарий тестирования:**
1) Зайти на localhost:3000
2) Кликнуть список литературы.
3) Кликнуть на логотип Step_to u
4) Убедиться, что вас перекинуло на localhost:3000

**Comment by Daniiar** [comment]
Time planned: 1,5
Time spend: 1,0
