### ISSUE TITLE
Добавление функционала в ЛКП, создать страничку "Моя литература"

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#52]
**Предыстория:**
Заказчик пожелал видеть в ЛКП список литературы преподавателя.

**Задача:**
Создать кнопку "Моя литература". При клике на нее должна открыться новая страница со списком всех книг преподавателя.

**Методы решения:**
Создать новую вьюшку. Вывести список книг преподавателя.

**Сценарий тестирования:**
1) Зайти под логином teach1
2) Зайти в ЛКП
3) Кликнуть на кнопку "Моя литература", вас должно перекинуть на новую страницу.
4) Увидеть список всех книг преподавателя.

**Comment by IlyaSvetlichnii** [comment]
Time planned: 1

**Comment by IlyaSvetlichnii** [comment]
Time spent: 1.5
