### ISSUE TITLE
Добавление функционала в ЛКП, добавление, удаление, скачивание книги.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#53]
К выполнению этого тикета переходить только после тикета #52

**Предыстория:**
Заказчик пожелала производить все манипуляции с книгами в ЛКП, в "Моя литература"

**Задача:**
В ЛКП, в списке "Моя литература". Напротив каждой книги добавить кнопки, скачать, удалить.
Перенести функционал добавление книги, со списка литературы, в ЛКП, на страницу "Моя литература."

**Методы решения:**
Создать вьюшку.
Кнопка "Скачать" в проекте уже реализована. Просмотрите как она сделана.
Кнопка "Удалить", написать action destroy, прописать роуты.
Кнопка "Добавить", перенести если нужно метод в другой контроллер.

**Сценарий тестирования:**
1) Зайти под логином teach1
2) Зайти в ЛКП
3) Зайти в "Моя литература"
4) Увидеть список литературы. Добавить новую книгу.
5) Увидеть в списке литературы новую книгу.
6) Напротив новой книги кликнуть "Скачать"
7) Убедиться что книга скачалась.
6) Напротив новой книги кликнуть "Удалить"
7) Убедиться что книги нету в списке преподавателя.

**Comment by IlyaSvetlichnii** [comment]
Time planned: 0.5
Time spent: 0.5
