### ISSUE TITLE
Добавление функционала в ЛКП, добавить страничку "Мои студенты"

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#54]
**Предыстория:**
Заказчик пожелал добавить в ЛКП, страничку "Мои студенты". Со списком всех студентов у этого преподавателя.

**Задача:**
В ЛКП, добавить кнопку "Мои студенты". При клике на неё переходим на новую страницу, со списком всех студентов прикрепленных к этому преподавателю. Вывести Имя, Телефон, Skype, Email студента.

**Методы решения:**.

**Сценарий тестирования:**
1) Зайти под логином преподавателя
2) Зайти в ЛКП.
3) Увидеть кнопку "Мои студенты", кликнуть на неё, должно перекинуть на новую страницу
4) Увидеть список студентов прикрепленных к этому преподавателю, их Имя, телефон, Skype, email.

**Comment by IlyaSvetlichnii** [comment]
time planned: 1
time spent: 0.5
