### ISSUE TITLE
Добавить в Navbar кнопку "Преподаватели."

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#55]
**Предыстория:**
Заказчик хочет видеть в навбаре кнопку "Преподаватели". Со списком всех преподавателей.

**Задача:**
Добавить в Navbar кнопку "Преподаватели". При клике на неё должен выводиться  список всех преподавателей. Их имя.

**Методы решения:**
В layouts добавить ссылку.

**Сценарий тестирования:**
1) Кликнуть в Navbare на кнопку "Преподаватели"
2) Перейти на новую страницу.
3) Увидеть список всех преподавателей и их имена.

**Comment by Daniiar** [comment]
Time planned: 1.5
Time spend: 1.0
