### ISSUE TITLE
Добавить поля в модель User и вьюшку registrations/new

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#56]
Выполнять этот тикет после выполнения тикета #55 

**Предыстория:**
Заказчик хочет чтобы, преподаватель заполнил у себя в профиле Описание о себе, чтобы вывести это на страничку "Наши преподаватели"

**Задача:**
В вьюшке registrations/new добавить поле описание
Добавить к модели User поля Описание Вывести их на страничку "Наши преподаватели"
Добавить в seed.rb поле описание, заполнить нормальным описанием преподавателя.

**Методы решения:**
В модель User добавить поля description:text
С помощью хелперов добавить поле description  во вьюшке registrations/new

**Сценарий тестирования:**
1) Зайти под логином преподавателя.
2) Отредактировать преподавателю поле описание и сохранить.
3) Зайти на страничку "Наши преподаватели"
4) Увидеть описание преподавателя.
5) Дропнуть базу. Прогнать миграции и seed.rd
6) Зайти на страничку "Наши преподаватели"
7) Увидеть заполненное сидами поле описание у преподавателей.

**Comment by Daniiar** [comment]
Time planned: 4.0
Time spend: 3.5
