### ISSUE TITLE
Добавить аватарку в профиль преподавателя.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#57]
**Предыстория:**
Заказчик хочет, чтобы на странице "Наши преподаватели" была фотка преподавателя.

**Задача:**
Подключить гем paperclip. Добавить аватарку преподавателю.
Вывести аватарки преподавателей на страничку "Наши преподаватели".
Добавить в сиды, чтобы картинки брал из папки assets.

**Методы решения:**
Читать документацию paperclipa
https://github.com/thoughtbot/paperclip
либо раздатку 

**Сценарий тестирования:**
1) Зайти за преподавателя.
2) Кликнуть "Редактировать профиль"
3) Добавить фотку препода. Сохранить
4) Зайти на страницу "Наши преподаватели"
5) Увидеть аватарки преподавателей

**Comment by Daniiar** [comment]
Time planned: 2
Time spend: 3

**Comment by KarambaKG** [comment]
Тикет проверен, работает.

**Comment by KarambaKG** [comment]
Тикет проверен, работает.
