### ISSUE TITLE
Добавить функционал в ЛКП, отправка домашних заданий студентам.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#58]
**Предыстория:**
Нужен функционал отправки домашних заданий из ЛКП студентам.

**Задача:**
Вернуть удаленный функционал отправки домашних заданий из ЛКП студентам.

**Методы решения:**
Откатиться на коммиты в которых был этот функционал. Копировать, вернуться обратно на свежий коммит и вставить)

**Сценарий тестирования:**
1) Зайти в ЛКП
2) Увидеть функционал отправки ДЗ студентам.
3) Отправить ДЗ студенту.
4) Зайти в ЛКС
5) Убедиться что ДЗ пришло.

**Comment by Daniiar** [comment]
Time planned: 2
Time spend: 2

**Comment by KarambaKG** [comment]
Тикет проверен.
