### ISSUE TITLE
Добавить функционал в ЛКС, дать возможность прикреплять файл

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#60]
К этому тикету приступать после тикета #58 и #59 

**Предыстория:**
Заказчик пожелал, чтобы у студента была возможность прикреплять файл и отправлять преподу как выполненную домашку. Препод должен иметь возможность скачать этот прикрепленный файл.

**Задача:**
Добавить функционал в ЛКС прикрепления файла и отправки его как ДЗ преподу.

**Методы решения:**

**Сценарий тестирования:**
1) Зайти под логином препода.
2) Отправить ДЗ студенту.
3) Зайти под логином студента
4) Скачать файл ДЗ и исправить информацию в нем.
5) Прикрепить измененный файл к домашке и отправить его преподу.
6) Зайти под логином препода.
7) Кликнуть "ДЗ на проверку"
8) Увидеть ДЗ на проверку, скачать файл
9) Убедиться что информация точно такая же, какую изменил студент.

**Comment by KarambaKG** [comment]
Time planned: 4

**Comment by IlyaSvetlichnii** [comment]
Time spent: 7 - предыдущая бизнес логика не соответствовала новой, пришлось немного отрефаторить
