### ISSUE TITLE
Добавить функционал в ЛКП, история ДЗ студента со статусом true и false.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#61]
**Предыстория:**
Заказчик хочет, чтобы преподаватель видел историю ДЗ студента и их статус.

**Задача:**
В ЛКП на странице "Мои студенты", напротив каждого студента добавить кнопку "История ДЗ". При клике на неё открывается новая страница. Где выводится информация этого студента, Имя, телефон, скайп, почта. Также выводиться список всех домашних заданий этого студента и их статус. 
Когда ДЗ отправлено преподавателем, оно появляется в истории студента со статусом "Sent". (вывести этот статус напротив ДЗ).

**Методы решения:**
Использовать булевое поле модели homework_assignments (is_done).

**Сценарий тестирования:**
1) Зайти под логином преподавателя
2) Зайти в ЛКП
2) Отправить студенту ДЗ
3) Кликнуть на кнопку "Мои студенты"
4) Кликнуть на кнопку "История ДЗ" напротив студента, которому отправили ДЗ
5) Увидеть в истории студента, ДЗ со статусом false

**Comment by KarambaKG** [comment]
Time planned: 8

**Comment by IlyaSvetlichnii** [comment]
Time spent: 2

**Comment by KarambaKG** [comment]
Тикет проверен.
