### ISSUE TITLE
Добавить функционал в ЛКП, проверенные ДЗ отмечаются как проверенные.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#62]
К этому тикету приступать только после тикета #59 #58 #61

**Предыстория:**
Заказчик хочет:
Когда преподаватель проверил домашнее задание, он помечает его как проверенное и оно исчезает из его списка, остаётся лишь при просмотра истории студента.

**Задача:**
На страничке "ДЗ на проверку", надо создать кнопку "Проверено", при клике на которую, статус ДЗ меняется на "true". И ДЗ пропадает со страницы "ДЗ на проверку", а в истории
 ДЗ студента статус тоже меняется на true.

**Методы решения:**
1) Использовать модель homework_assignments и его  булевое поле is_done
2) в action использовать update_attribute

**Сценарий тестирования:**
1) Зайти под логином преподавателя
2) Зайти в ЛКП
3) Отправить ДЗ студенту
4) Зайти под логином студента
5) Отправить ДЗ преподу обратно
6) Зайти под логином препода
7) Зайти в ЛКП
8) Кликнуть на кнопку "ДЗ на проверку"
9) Увидеть ДЗ от студента напротив неё, кликнуть на кнопку "Проверено"
10) Увидеть что ДЗ пропало из списка "ДЗ на проверку"
11) Зайти в историю ДЗ студента.
12) Увидеть что статус ДЗ поменялся на true.

**Comment by KarambaKG** [comment]
Time planned: 1

**Comment by IlyaSvetlichnii** [comment]
Time spent: 1.5
