### ISSUE TITLE
Переделать страницу ЛКС

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#65]
**Предыстория:**
Нужен нормальный ЛКС, с нормальной, простой логикой, понятной всем.

**Задача:**
На странице ЛКС, вывести все ДЗ этого студента с их статусами и названиями. Название ДЗ сделать ссылкой. При клике на которую, должно переходить на новую страницу, где студент может скачать прикрепленный файл и завершить ДЗ.

**Методы решения:**
Отрефакторить код страницы ЛКС. Создать форму для принятия, отправки ДЗ файла.

**Сценарий тестирования:**
1) Зайти в ЛКС
2) Увидеть все ДЗ с их названиями и статусами.
3) Кликнуть на название ДЗ
3) Увидеть кнопку "Скачать файл"
4) Проверить функционал

**Comment by KarambaKG** [comment]
Time planned: 6

**Comment by IlyaSvetlichnii** [comment]
Time spent: 4
