### ISSUE TITLE
Добавить функционал в ЛКП. Преподаватель может просмотреть созданное им ДЗ.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#76]
**Предыстория:**
Заказчик сказал, что учителя могут забыть что они создали за ДЗ.

**Задача:**
Дать возможность просмотра ДЗ преподавателя. На странице "Домашние задания" напротив кнопки "Удалить" добавить кнопку "Просмотреть". 
![default](https://cloud.githubusercontent.com/assets/19923955/20090569/1c61805c-a5b8-11e6-9639-77de65c013b9.jpg)

При клике на неё должно выйти окно просмотра ДЗ, наподобие такого.
![default](https://cloud.githubusercontent.com/assets/19923955/20090438/51a9b3b6-a5b7-11e6-9a1c-09019c3a662e.jpg)

**Методы решения:**
Написать action show_homework в homeworks_controller
Создать для него вьюшку, прописать роуты

**Сценарий тестирования:**
1) Войти под преподавателем.
2) Перейти в ЛКП
3) Перейти в ДЗ
4) Кликнуть на ссылку "Просмотреть"
5) Увидеть что есть в ДЗ

**Comment by IlyaSvetlichnii** [comment]
Time planned: 1

**Comment by IlyaSvetlichnii** [comment]
Time spent: 0.6
