### ISSUE TITLE
Добавить функционал в ЛКП. ДЗ можно отправить без файла.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#77]
**Предыстория:**
Заказчик,  сказал, что преподаватель может отправить ДЗ без файла.

**Задача:**
Сделать отправку ДЗ без прикрепленного файла.

**Методы решения:**
Возможно в геме paperclip есть валидация на nil. Посмотреть документацию gema.

**Сценарий тестирования:**
1) Войти под преподавателем
2) Перейти в ДЗ.
3) Кликнуть создать ДЗ
4) Создать ДЗ без прикрепленного файла.
5) Отправить созданное ДЗ студенту.
6) Войти под студентом.
7) Отправить ДЗ обратно преподавателю
8) Войти под преподавателем.
9) Войти в ДЗ на проверку.
10) Проверить его.

**Comment by Daniiar** [comment]
Time planned: 2
Time spent: 8
