### ISSUE TITLE
Студент должен отправить результат домашнего задания только 1 раз.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#78]
**Предыстория:**
Заказчик сказал, что студент только 1 раз должен отправить решенное ДЗ преподавателю.

**Задача:**
Студент должен отправить результат домашнего задания только 1 раз.
При клике кнопки создать Homework result она должна исчезнуть.

**Методы решения:**
При клике кнопки создать Homework result у нас меняется статус ДЗ на Unchecked. Можно написать условие, если ДЗ со статусом "Sent" отображать кнопку "создать Homework result", иначе не выводить "создать Homework result".

**Сценарий тестирования:**
1) Войти под преподавателем.
2) Отправить ДЗ студенту.
3) Войти под студентом.
4) Перейти на присланную ДЗ
5) Кликнуть на кнопку "создать Homework result"
6) Убедиться что кнопка "создать Homework result" исчезла и статус ДЗ поменялся на Unchecked
7) Войти под преподавателем
8) Перейти на страницу "ДЗ на проверку"
9) Проверить ДЗ
10) Убедиться что статус ДЗ поменялся на "Checked"

**Comment by IlyaSvetlichnii** [comment]
Time planned: 1

**Comment by IlyaSvetlichnii** [comment]
Time spent: 0.5
