### ISSUE TITLE
Добавить в ЛКП график расписания

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#79]
**Предыстория:**
Заказчик хочет видеть график расписания преподавателя.

**Задача:**
Сверстать график расписания преподавателя.
Время на графике 7:00 до 23:00
![default](https://cloud.githubusercontent.com/assets/19923955/20093187/e889a76a-a5c5-11e6-9b5a-65b5174e678f.jpg)

**Методы решения:**

**Сценарий тестирования:**
1) Войти под преподавателем
2) Перейти в ЛКП
3) Увидеть график

**Comment by IlyaSvetlichnii** [comment]
Time planned: 2

**Comment by IlyaSvetlichnii** [comment]
Time spent: 2
