### ISSUE TITLE
Отобразить расписание на странице наши преподаватели, и только цвета занятости.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#83]
**Предыстория:**
Заказчик хочет чтобы на странице мои преподаватели, отображалось расписание преподавателя.
Видны были только цвета.

**Задача:**
Отобразить расписание на странице наши преподаватели, и только цвета занятости.

**Методы решения:**

**Сценарий тестирования:**
1) Зайти в Наши преподаватели
2) Увидеть напротив каждого преподавателя график его расписания. Помеченный различными цветами.

**Comment by IlyaSvetlichnii** [comment]
Time planned: 2

**Comment by IlyaSvetlichnii** [comment]
Time spent: 1.5
