### ISSUE TITLE
В ЛКС добавить мини расписание для студента.

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#84]
**Предыстория:**
Заказчик хочет видеть в ЛКС у студента мини расписание. С его днями занятий и временем.

**Задача:**
1) В ЛКС сверстать график
2) Отобразить время под днем недели если у студента назначен урок.

**Методы решения:**

**Сценарий тестирования:**
1) Зайти в ЛКС увидеть график.
2) Назначить студенту урок.
3) Убедиться что он отобразился у него на графике.

**Comment by IlyaSvetlichnii** [comment]
Time planned: 3

**Comment by IlyaSvetlichnii** [comment]
Time spent: 2
