### ISSUE TITLE
Историю студента сделать в табличном виде

### ISSUE THREAD

**Issue by KarambaKG** [esdp-2016-Team3/StepToUniverse#85]
**Предыстория:**
Заказчик желает видеть историю студента, сделать в табличном виде.

**Задача:**
Сделать историю студента сделать в табличном виде

**Методы решения:**
border=1

**Сценарий тестирования:**
1) Зайти в ЛКП
2) Перейти в "Мои студенты"
3) Кликнуть на студента
4) Увидеть историю его ДЗ в таблице.

**Comment by Daniiar** [comment]
Time planned: 2
Time spent: 4
