### ISSUE TITLE
Cоздать функциональность подтверждения регистрации администратором 

### ISSUE THREAD

**Issue by IlyaSvetlichnii** [esdp-2016-Team3/StepToUniverse#9]
Описание:
 В панели администратора необходимо создать функционал  с подтверждением регистрации пользователем. После успешного заполнения регистрации анонимным пользователем он становится неактивным. В панели администратор видит запросы пользователей и может активировать их или отказать в активации. Новый пользователь будет иметь возможность пользоваться функционалом системы только после подтверждения регистрации.

Сценарии тестирования:

Функционал: Подтверждение администраторам запрос
Допустим залогинился в панель администратора
Если я прохожу по ссылке "запросы на регистрацию"
То вижу список неактивированных пользователей 

Допустим я нахожусь на странице "запросы на регистрацию"
Если я выбираю неактивированного пользователя
То на страницу профиля пользователя у меня есть возможность подтвердить или отказать в регистрации 

Допустим я нахожусь на странице профиля неактивированого пользователя
Если я активирую пользователя
То он имеет возможность пользоваться функционалом системы

Допустим я нахожусь на странице профиля неактивированного пользователя
Если я отклоняю его запрос
То неактивированный пользователь видит у себя на странице что его запрос отклонили

**Comment by tolykg** [comment]
time planed: 50 min
time spent: 60 min
